[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/sam"
  to   = "/.netlify/functions/sam"
  status = 200

[[redirects]]
  from = "/api/track"
  to   = "/.netlify/functions/track"
  status = 200

[[redirects]]
  from = "/api/sam-detail"
  to   = "/.netlify/functions/sam-detail"
  status = 200
